---
title: "workshop7"
author: "Antoneely Calizaya"
date: "3/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(skimr)

coffee_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-07/coffee_ratings.csv')

skim(coffee_ratings)
```
Option 1 to convert to factors
```{r}
coffee_ratings<-coffee_ratings%>%
  mutate(
    species=as_factor(species),
    country_of_origin=as_factor(country_of_origin)
  )
```

Option 2 to convert to factors
```{r}
coffee_ratings$owner<-as_factor(coffee_ratings$owner)

coffee_ratings%>%count(country_of_origin, sort=TRUE)

coffee_ratings<-coffee_ratings%>%
  mutate(
    country_of_origin_lumped=fct_lump(country_of_origin,n=14)
  )

coffee_ratings%>%count(country_of_origin_lumped, sort=TRUE)
```
```{r}
#use gglpot with geom_col where one of the variables is country_of_origin_lumped

coffee_ratings%>%
  mutate(
    country_of_origin_lumped=fct_reorder(country_of_origin_lumped,total_cup_points,sum)
  )%>%
  ggplot(aes(
    total_cup_points, country_of_origin_lumped, fill=total_cup_points))+
  geom_col()+
  labs(
    title = "Total cup points per country of origin",
    caption = "Figure 1",
    x = "Total cup points",
    y = "Country of origin(lumped)"
  )

```
```{r}
coffee_ratings%>%
  ggplot(aes(
    altitude, country_of_origin_lumped, fill=altitude))+
  geom_col()+
  labs(
    title = "Total bad weight per country of origin",
    caption = "Figure 1",
    x = "Bag weight",
    y = "Country of origin(lumped)"
  )

```

distribution total_cup_points
```{r}
coffee_ratings%>%
  ggplot(aes(
    total_cup_points
  ))+
  geom_histogram()

```
boxplot
```{r}
coffee_ratings%>%
  boxplot(total_cup_points)
```



```{r}
coffee_ratings%>%
  ggplot(aes(
    total_cup_points, country_of_origin_lumped, fill=total_cup_points))+
  geom_bar()+
  labs(
    title = "Total cup points per country of origin",
    caption = "Figure 1",
    x = "Total cup points",
    y = "Country of origin(lumped)"
  )
```


Change is made but only in the output
```{r}
coffee_ratings%>%
  mutate(
    species=as_factor(species),
    country_of_origin=as_factor(country_of_origin)
    
  )
```



