---
title: "Workshop2"
author: "Antoneely Calizaya"
date: "3/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Link](https://github.com/rstudio/cheatsheets/blob/main/rmarkdown-2.0.pdf) 

```{r}
# Get the Data

# Read in with tidytuesdayR package 
install.packages("tidytuesdayR")
library(tidyverse)
# This loads the readme and all the datasets for the week of interest

# Either ISO-8601 date or year/week works!

tuesdata <- tidytuesdayR::tt_load('2021-05-18')
tuesdata <- tidytuesdayR::tt_load(2021, week = 21)

survey <- tuesdata$survey

# Or read in the data manually

survey <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')
data%<%head()

```

```{r}
survey_short<-survey%>%
  filter(
    country=="United States" |
      country=="USA" | 
      country=="US" | 
      country=="U.S." | 
      country=="United States of America" |
      country=="Usa"
    )
```

Arrange ascending order
```{r}
survey_short%>%arrange(annual_salary)%>%
  select(industry, annual_salary)
```

Arrange descending order
```{r}
survey_short%>%arrange(desc(annual_salary))%>%
  select(industry, annual_salary)

survey_short%>%count(industry, sort=TRUE)
```
Grouppings and new variables
```{r}
survey_short%>%
  mutate(total_salary=annual_salary+other_monetary_comp)%>%
  select(industry, total_salary, annual_salary, other_monetary_comp)

survey_short%>%
  mutate(average_salary=mean(annual_salary, na.rm = TRUE))%>%
  select(industry, average_salary)

survey_short%>%
  group_by(industry)%>%
  mutate(average_salary=mean(annual_salary, na.rm = TRUE))%>%
  select(industry, average_salary)%>%
  arrange(desc(average_salary))
ungroup()

survey_short%>%
  group_by(industry)

#add a new variable max_salary which is maximum salary per industry

survey_short%>%
  group_by(industry)%>%
  mutate(max_salary=max(annual_salary, na.rm = TRUE))%>%
  select(industry, max_salary)%>%
  arrange(desc(max_salary))%>%
ungroup()

survey_short%>%
  group_by(industry, gender)%>%
  mutate(average_salary=mean(annual_salary, na.rm = TRUE))%>%
  select(industry, gender, average_salary)%>%
  arrange(desc(average_salary))%>%
ungroup()
```


```{r}
survey_short%>%
  group_by(gender, industry)%>%
  mutate(average_salary=mean(annual_salary, na.rm = TRUE))%>%
  select(gender, industry, average_salary)%>%
  arrange(desc(average_salary))%>%
ungroup()

```

summarising data

```{r}
survey_short%>%
  group_by(industry)%>%
  summarise(average_salary=mean(annual_salary, na.rm = TRUE))

survey_short%>%
  group_by(industry, gender)%>%
  summarise(average_salary=mean(annual_salary, na.rm = TRUE))

```
```{r}
survey_short%>%
  group_by(gender,industry)%>%
  summarise(average_salary=mean(annual_salary, na.rm = TRUE))
```
```{r}
survey_short%>%
  group_by(industry, gender)%>%
  summarise(
    average_salary=mean(annual_salary, na.rm = TRUE),
    max_salary=max(annual_salary, na.rm = TRUE)
    )
```
```{r}
survey_short_veryshort<-survey_short%>%
  select(industry, gender, annual_salary)

#if annual_salary is more than 700000 than your annual_salary_level is high, otherwise it is low 

survey_short_veryshort%>%
  mutate(annual_salary_level=case_when(
    annual_salary>700000 ~ "high",
    TRUE ~ "low"
    )
  )%>%
  arrange(desc(annual_salary))
```
```{r}
survey_short_veryshort%>%
  mutate(annual_salary_level=case_when(
    annual_salary>700000 ~ "high",
    annual_salary>70000 & annual_salary<=70000 ~ "middle",
    TRUE ~ "low"
    )
  )%>%
  arrange(desc(annual_salary))
```
```{r}
survey_short_veryshort%>%
  mutate(highly_paid_women=case_when(
   gender == "Woman" & annual_salary>50000 ~ "high",
    TRUE ~ "low"
    )
  )%>%
  arrange(desc(annual_salary))
```

```{r}
install.packages("ggplot2")
library(ggplot2)
data(mpg)
mpg%>%
  ggplot(
    aes(displ, hwy, colour = manufacturer, size = model, shape = year)

data(mpg)
mpg%>%
  ggplot(
    aes(displ, hwy, colour = manufacturer, size = model, shape = year)
  ) + geom_point()
```

```{r}
data(mpg)
mpg%>%
  ggplot(
    aes(displ, hwy, colour = manufacturer, size = model, shape = year)
  ) + geom_point()
```





